app = 'one-on-one'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 2137
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[mounts]]
  source = "volume"
  destination = "/data"
  initial_size = "1gb"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
